# Generated by Django 5.2.1 on 2026-02-03 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Leitner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('leitner_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(choices=[('new', 'New'), ('1_day', '1 Day'), ('3_days', '3 Days'), ('7_days', '7 Days'), ('mastered', 'Mastered')], default='new', max_length=20)),
            ],
            options={
                'db_table': 'leitner',
                'indexes': [models.Index(fields=['user_id'], name='leitner_user_id_886839_idx'), models.Index(fields=['user_id', 'type'], name='leitner_user_id_6fb87c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quiz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quiz',
                'indexes': [models.Index(fields=['user_id'], name='quiz_user_id_f8bcad_idx'), models.Index(fields=['user_id', 'date'], name='quiz_user_id_9aa7f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurvivalGame',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('survival_game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('lives', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survival_game',
                'indexes': [models.Index(fields=['user_id'], name='survival_ga_user_id_88b28a_idx'), models.Index(fields=['user_id', 'date'], name='survival_ga_user_id_8e9e8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('english', models.TextField(db_index=True)),
                ('persian', models.TextField()),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='team1.category')),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField()),
                ('optiona', models.CharField(blank=True, max_length=255, null=True)),
                ('optionb', models.CharField(blank=True, max_length=255, null=True)),
                ('optionc', models.CharField(blank=True, max_length=255, null=True)),
                ('optiond', models.CharField(blank=True, max_length=255, null=True)),
                ('word', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='team1.word')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='team1.question')),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='team1.quiz')),
            ],
            options={
                'db_table': 'user_answer',
                'indexes': [models.Index(fields=['user_id'], name='user_answer_user_id_bf874f_idx'), models.Index(fields=['quiz'], name='user_answer_quiz_id_29971b_idx'), models.Index(fields=['question'], name='user_answer_questio_47cb98_idx'), models.Index(fields=['user_id', 'quiz', 'question'], name='user_answer_user_id_635deb_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_word_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('last_check_date', models.DateField(blank=True, null=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('leitner', models.ForeignKey(db_column='leitner_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='team1.leitner')),
                ('word', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='team1.word')),
            ],
            options={
                'db_table': 'user_words',
                'indexes': [models.Index(fields=['word'], name='user_words_word_id_ce7381_idx'), models.Index(fields=['leitner'], name='user_words_leitner_a24290_idx'), models.Index(fields=['user_id'], name='user_words_user_id_27aaa5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['word'], name='question_word_id_fe97f6_idx'),
        ),
    ]
