# Generated by Django 4.2.27 on 2026-02-10 15:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=50, verbose_name='Exam Section')),
                ('system', models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('general', 'General English')], max_length=50, verbose_name='Exam System')),
                ('exam_time_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(36000)], verbose_name='Exam Time (seconds)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Feedback Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Attempt Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('graded', 'Graded')], default='draft', max_length=20, verbose_name='Status')),
                ('response_text', models.TextField(blank=True, null=True, verbose_name='Text Response')),
                ('response_voice_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Voice File Path')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to='team3.exam', verbose_name='Exam')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_exams', to='team3.feedback', verbose_name='Feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Exam',
                'verbose_name_plural': 'User Exams',
                'db_table': 'user_exam',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Question Number')),
                ('description', models.TextField(verbose_name='Question Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='team3.exam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['deleted_at'], name='feedback_deleted_548f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['section', 'system'], name='exam_section_3c1be6_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['deleted_at'], name='exam_deleted_6d8485_idx'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['user', 'exam'], name='user_exam_user_id_87830a_idx'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['status'], name='ix_user_exam_status_active'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['deleted_at'], name='user_exam_deleted_09b776_idx'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['created_at'], name='user_exam_created_24a09b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userexam',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'exam', 'attempt_no'), name='active_attempt_exam_user_uq'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'number'], name='question_exam_id_77698e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['deleted_at'], name='question_deleted_386429_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('exam', 'number'), name='active_number_exam_question_uq'),
        ),
    ]
