package com.gramsense.persistence.entity.enumeration;

/**
 * @author Mehdi Kamali
 * @since 11/02/2026
 */
public enum GrammarTopic {

    // TENSE
    PRESENT_SIMPLE,
    PRESENT_CONTINUOUS,
    PAST_SIMPLE,
    PAST_CONTINUOUS,
    PRESENT_PERFECT,
    PAST_PERFECT,
    TENSE_CHOICE,

    // CONDITIONAL
    CONDITIONAL_ZERO,
    CONDITIONAL_FIRST,
    CONDITIONAL_SECOND,
    CONDITIONAL_THIRD,
    CONDITIONAL_MIXED,
    WISH_IF_ONLY,

    // MODAL
    MODAL_ABILITY_PERMISSION,
    MODAL_OBLIGATION,
    MODAL_POSSIBILITY,
    MODAL_PERFECT,

    // VOICE
    PASSIVE_VOICE,
    CAUSATIVE_HAVE_GET,
    REPORTED_SPEECH,

    // VERB_PATTERN
    GERUND_INFINITIVE,
    RELATIVE_CLAUSES,

    // COMPARISON
    ARTICLES,
    COMPARISON
}
