# Generated by Django 4.2.27 on 2026-02-13 11:40

from django.db import migrations, models


def _listening_to_speaking(apps, schema_editor):
    Submission = apps.get_model('team11', 'Submission')
    QuestionCategory = apps.get_model('team11', 'QuestionCategory')

    Submission.objects.filter(submission_type='listening').update(submission_type='speaking')
    QuestionCategory.objects.filter(question_type='listening').update(question_type='speaking')


def _speaking_to_listening(apps, schema_editor):
    Submission = apps.get_model('team11', 'Submission')
    QuestionCategory = apps.get_model('team11', 'QuestionCategory')

    Submission.objects.filter(submission_type='speaking').update(submission_type='listening')
    QuestionCategory.objects.filter(question_type='speaking').update(question_type='listening')


class Migration(migrations.Migration):

    dependencies = [
        ('team11', '0004_add_sample_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListeningSubmission',
            new_name='SpeakingSubmission',
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='question_type',
            field=models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20),
        ),
        migrations.RunPython(_listening_to_speaking, _speaking_to_listening),
    ]
