# Generated by Django 4.2.27 on 2026-02-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team11', '0006_update_writing_min_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingsubmission',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='speaking_details', serialize=False, to='team11.submission'),
        ),
    ]
